version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: agrohelp
      POSTGRES_PASSWORD: agrohelp123
      POSTGRES_DB: agrohelp_local
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:
